export const LAHORE_CITY = 'Lahore';

export const LAHORE_AREAS = [
    'Johar Town',
    'Wapda Town',
    'DHA',
    'Gulberg',
    'Model Town',
    'Garden Town',
    'Bahria Town',
    'Valencia Town',
    'Faisal Town',
    'Iqbal Town',
    'Cantt',
    'Askari',
    'Township',
    'Allama Iqbal Town',
    'Muslim Town',
    'Shadman',
    'Jail Road',
    'Ferozepur Road',
    'Raiwind Road',
    'Thokar Niaz Baig',
    'Canal Road',
    'Defence Road',
    'Lake City',
    'Paragon City',
    'Samanabad',
    'Shahdara',
    'Mughalpura',
    'Sabzazar',
    'Ravi Road',
    'Mall Road'
];
